name: Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug GH_TOKEN availability
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "ERROR: GH_TOKEN is empty!"
            exit 1
          else
            echo "GH_TOKEN is set."
          fi
      - name: Merge the pull request
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh auth status
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --delete-branch --admin
